apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tests.srossross.github.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: srossross.github.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tests
    # singular name to be used as an alias on the CLI and for display
    singular: test
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Test
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    # - tst
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: testruns.srossross.github.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: srossross.github.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: testruns
    # singular name to be used as an alias on the CLI and for display
    singular: testrun
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TestRun
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tr
